# Generated by Django 4.2.6 on 2023-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='images/user.jpg', upload_to='images/'),
        ),
    ]
