# Generated by Django 4.2.6 on 2023-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_main', '0003_alter_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/products/'),
        ),
    ]
